@startuml 收款全流程状态机

hide empty description
scale 516 width

[*] --> A1

' 初始
A1 --> A12 : 系统 引擎审核通过
A1 --> A3 : 系统 引擎审核不通过且需要手动关联订单
A1 --> A2 : 系统 引擎审核不通过且自动关联订单
A1 --> A4 : 系统 判定付款人名称缺失时

' 关联订单待筛查
A2 --> A4 : 系统 引擎审核不通过
A2 --> A12 : 系统 引擎审核通过
A2 --> A6 : 系统 引擎审核不通过且需要机构审核

' 待关联订单
A3 --> A2 : 用户 手动关联订单
A3 --> A7 : 运营 发起退款

' 待初审
A4 --> A5 : 风控 审核通过
A4 --> A7 : 运营 发起退款
A4 --> A3 : 风控 审核驳回

' 待复审
A5 --> A4 : 风控 审核驳回
A5 --> A6 : 风控 (申报类渠道)复审通过
A5 --> A11 : 风控 (调单类渠道)复审通过
A5 --> A7 : 运营 发起退款

' 待机构申报及入账审核
A6 --> A11 : 系统 机构审核通过
A6 --> A8 : 系统 机构审核驳回，直接退款

' 退款待复审
A7 --> A3 : 运营 退款审核驳回
A7 --> A8 : 运营 退款审核通过且无需补充退款信息
A7 --> A13 : 运营 退款审核通过且无需补充退款信息

' 退款信息待补充
A13 --> A14 : 用户 补充退款信息

' 退款信息待审核
A14 --> A8 : 风控 补充退款信息审核通过
A14 --> A13 : 风控 补充退款信息审核驳回

' 退款中
A8 --> A10 : 系统 退款成功
A8 --> A9 : 系统 退款失败

' 退款失败
A9 --> A7 : 运营 重新发起退款
' 退款失败 退回到 入账初审复审？？？这玩意，去掉算了
' A9 --> A4 : ？？？
' A9 --> A5 : ？？？
' 退款失败 退回到 待关联订单？？？这啥玩意+1
' A9 --> A3 : ？？？

' 已退款
A10 --> [*]

' 已入账
A11 --> [*]

' 已入账自动
A12 --> [*]

' 显示状态

' 初始
A1 : 【初始】
A1 : MPS用户 不显示
A1 : OPS运营 不显示
A1 : OPS风控 不显示
A1 : OPS清算 不显示

' 关联订单待筛查
A2 : 【关联订单待筛查】
A2 : MPS用户 待审核
A2 : OPS运营 待审核
A2 : OPS风控 关联订单待筛查
A2 : OPS清算 待审核

' 待关联订单
A3 : 【待关联订单】
A3 : MPS用户 待关联订单
A3 : OPS运营
A3 : OPS风控
A3 : OPS清算

' 待初审
A4 : 【待初审】
A4 : MPS用户 待审核
A4 : OPS运营
A4 : OPS风控
A4 : OPS清算

' 待复审
A5 : 【待复审】
A5 : MPS用户 待审核
A5 : OPS运营
A5 : OPS风控
A5 : OPS清算

' 待机构申报及入账审核
A6 : 【待机构申报及入账审核】
A6 : MPS用户 待审核
A6 : OPS运营
A6 : OPS风控
A6 : OPS清算

' 退款待复审
A7 : 【退款待复审】
A7 : MPS用户 待审核
A7 : OPS运营
A7 : OPS风控
A7 : OPS清算

' 退款中
A8 : 【退款中】
A8 : MPS用户 退款中
A8 : OPS运营
A8 : OPS风控
A8 : OPS清算 退款中

' 退款失败
A9 : 【退款失败】
A9 : MPS用户 退款中
A9 : OPS运营
A9 : OPS风控
A9 : OPS清算 退款失败

' 退款信息待补充
A13 : 【退款信息待补充】
A13 : MPS用户
A13 : OPS运营
A13 : OPS风控
A13 : OPS清算

' 退款信息待审核
A14 : 【退款信息待审核】
A14 : MPS用户
A14 : OPS运营
A14 : OPS风控
A14 : OPS清算

' 已退款
A10 : 【已退款】
A10 : MPS用户 已退款
A10 : OPS运营 已退款
A10 : OPS风控 已退款
A10 : OPS清算 已退款

' 已入账
A11 : 【已入账】
A11 : MPS用户 已入账
A11 : OPS运营 已入账
A11 : OPS风控 已入账
A11 : OPS清算 已入账

' 已入账自动
A12 : 【已入账自动】
A12 : MPS用户 已入账
A12 : OPS运营 已入账
A12 : OPS风控 已入账
A12 : OPS清算 已入账

@enduml