
@startuml 退款流程新增订单状态变化

hide empty description

[*] --> 待初审

待初审 -> 待复审

待复审 -> 退款信息待补充

退款信息待补充 -> 退款信息待审核: 用户在MPS端补充退款账户信息

退款信息待审核 -> 退款信息待补充: 风控同事在OPS端审核驳回

退款信息待审核 -> 退款中: 风控同事在OPS端审核通过

退款中 -> 已退款

已退款 --> [*]

@enduml
