@startuml 退款流程订单状态变化

hide empty description
scale 516 width

[*] --> 可退款状态集

可退款状态集 --> 退款待复审 : 运营 发起退款

退款待复审 --> 可退款状态集 : 运营 退款审核驳回
退款待复审 --> 退款信息待补充 : 运营 复审通过但需补充退款信息
退款待复审 --> 退款中 : 运营 复审通过且无需补充退款信息

退款信息待补充 --> 退款信息待审核 : 用户 补充退款信息

退款信息待审核 --> 退款中 : 风控 审核通过
退款信息待审核 --> 退款信息待补充 : 风控 审核驳回

退款中 --> 已退款 : 系统 退款成功
退款中 --> 退款失败 : 系统 退款失败

退款失败 --> 退款待复审 : 运营 重新发起退款

已退款 --> [*]

' 显示状态

' 可退款状态集
' 可退款状态集  : MPS用户
' 可退款状态集  : OPS运营 
' 可退款状态集  : OPS风控 
' 可退款状态集  : OPS清算 

' 退款待复审
退款待复审 : MPS用户 待审核
退款待复审 : OPS运营 退款待复审
退款待复审 : OPS风控 退款中
退款待复审 : OPS清算 退款待复审

' 退款信息待补充
退款信息待补充 : MPS用户 退款中
退款信息待补充 : OPS运营 退款中
退款信息待补充 : OPS风控 退款中
退款信息待补充 : OPS清算 退款中

' 退款信息待审核
退款信息待审核 : MPS用户 退款中
退款信息待审核 : OPS运营 退款中
退款信息待审核 : OPS风控 退款信息待审核
退款信息待审核 : OPS清算 退款中

' 退款中
退款中 : MPS用户 退款中
退款中 : OPS运营 退款中
退款中 : OPS风控 退款中
退款中 : OPS清算 退款中

' 退款失败
退款失败 : MPS用户 退款中
退款失败 : OPS运营 退款失败
退款失败 : OPS风控 退款中
退款失败 : OPS清算 退款失败

' 已退款
已退款 : MPS用户 已退款
已退款 : OPS运营 已退款
已退款 : OPS风控 已退款
已退款 : OPS清算 已退款

@enduml