
@startuml 退款流程新增订单状态变化

hide empty description

[*] --> 初始

待初审 --> 待复审 : 风控审核通过

待初审 --> 退款待复审 : 运营发起退款

待初审 --> 审核未通过: 风控审核驳回

待复审 --> 待初审 : 风控审核驳回

待复审 --> 待机构申报及入账审核 : (申报类渠道)风控复审通过

待复审 --> 已入账 : (调单类渠道)风控复审通过

待复审 --> 退款待复审 : 运营发起退款

退款待复审 --> 待关联订单 : 运营审核驳回

退款待复审 --> 退款中 : 运营审核通过

待机构申报及入账审核 --> 已入账 : 机构审核通过

待机构申报及入账审核 --> 退款中 : 机构审核驳回，直接退款

' [*] --> 待退款

' 待退款 -down-> 退款待复审

' 退款待复审 --> 退款中

' state 退款中 {
'     退款中--> 退款信息待补充
'     退款信息待补充 --> 退款信息待审核: 用户在MPS端补充退款账户信息
'     退款信息待审核 --> 退款信息待补充: 风控同事在OPS端审核驳回
'     退款信息待审核 --> 退款中: 风控同事在OPS端审核通过
' }

' 退款中 --> 已退款

' 已退款 --> [*]

@enduml
